version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "Quinn-p"
github_repo = "Cloud-Resume-Challenge"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::471112744928:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-fSc2D6S3Dw20"
cloudformation_execution_role = "arn:aws:iam::471112744928:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-PmOEwSUNuNDI"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-onxhsxmx83tw"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::471112744928:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-gjAY0jZpeS95"
cloudformation_execution_role = "arn:aws:iam::471112744928:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-rmASwseDtkEe"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-qih8tzy3r8dp"
image_repository = ""
region = "us-east-1"
